language: node_js

node_js:
    - "0.12"

before_install:
  - pushd "${HOME}"
  - curl -L "https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz" | gunzip -c | tar x
  - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
  - popd
  - cmake --version
  - env

script:
    - git submodule init
    - git submodule update
    - npm install
    - ./node_modules/.bin/grunt default docs
    - ./node_modules/.bin/grunt serve-test &
    - sleep 1
    - mkdir _build
    - cd _build
    - cmake -DCOVERAGE_TESTS=ON ..
    - ctest -VV -S ../cmake/travis_build.cmake || true
    - if [ -f test_failed ] ; then false ; fi

sudo: False
